# Generated by Django 3.2 on 2021-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0010_auto_20200729_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calorie_limit',
            field=models.IntegerField(null=True),
        ),
    ]
