# Generated by Django 3.2 on 2021-05-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0011_customer_calorie_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fityfeed.customer'),
        ),
    ]
