# Generated by Django 3.2 on 2021-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0015_auto_20210516_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
