# Generated by Django 3.2 on 2021-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0016_auto_20210516_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
